            # Nombre    Género      Pelo                                                                    Cejas       Cara                                                        Ojos                        Boca                Nariz                           Extras

personajes=[["Susan",   "mujer",    "largo","blanco","blanca","canoso","canosa","canas",                    "finas",    "alargada","alegre","contento","contenta",                  "marrones",                 "boca grande",      "nariz pequeña","nariz fina",   "mejillas","sonrosadas"],
            ["Claire",  "mujer",    "corto","pelirrojo","pelirroja","rojo","roja",                          "finas",    "redonda","redondeada","alegre","contento","contenta",      "marrones",                 "boca pequeña",     "nariz pequeña","nariz fina",   "sombrero","gorro","gorra","pendientes","pendiente", "gafas","lentes"],
            ["David",   "hombre",   "corto","rubio","rubia","amarillo","amarilla",                          "finas",    "alargada","alegre","contento","contenta",                  "marrones",                 "boca grande",      "nariz pequeña","nariz fina",   "bigote","barba"],
            ["Anne",    "mujer",    "corto","negro","negra","oscuro","oscura",                              "finas",    "redonda","redondeada","triste","enfadado","enfadada",      "marrones",                 "boca pequeña",     "nariz grande","nariz gruesa",  "pendientes","pendiente"],
            ["Robert",  "hombre",   "corto","castaño","castaña",                                            "finas",    "alargada","triste","enfadado","enfadada",                  "azules","azulados",        "boca grande",      "nariz grande","nariz gruesa",  "mejillas","sonrosadas"],
            ["Anita",   "mujer",    "largo","rubio","rubia","amarillo","amarilla",                          "finas",    "redonda","redondeada","alegre","contento","contenta",      "azules","azulados",        "boca pequeña",     "nariz pequeña","nariz fina",   "mejillas","sonrosadas"],
            ["Joe",     "hombre",   "corto","rubio","rubia","amarillo","amarilla",                          "gruesas",  "alargada","alegre","contento","contenta",                  "marrones",                 "boca pequeña",     "nariz pequeña","nariz fina",   "gafas"],
            ["George",  "hombre",   "corto","blanco","blanca","canoso","canosa","canas",                    "finas",    "alargada","triste","enfadado","enfadada",                  "marrones",                 "boca grande",      "nariz pequeña","nariz fina",   "sombrero","gorro","gorra"],
            ["Bill",    "hombre",   "corto","calvo","calva","pelirrojo","pelirroja","rojo","roja",          "finas",    "alargada","alegre","contento","contenta",                  "marrones",                 "boca pequeña",     "nariz pequeña","nariz fina",   "mejillas","sonrosadas"],
            ["Alfred",  "hombre",   "largo","pelirrojo","pelirroja","rojo","roja",                          "finas",    "alargada","triste","enfadado","enfadada",                  "azules","azulados",        "boca pequeña",     "nariz pequeña","nariz fina",   "bigote","barba"],
            ["Max",     "hombre",   "corto","negro","negra","oscuro","oscura",                              "finas",    "redonda","redondeada","alegre","contento","contenta",      "marrones",                 "boca grande",      "nariz grande","nariz gruesa",  "bigote","barba"],
            ["Tom",     "hombre",   "corto","calvo","calva","negro","negra","oscuro","oscura",              "finas",    "alargada","alegre","contento","contenta",                  "azules","azulados",        "boca pequeña",     "nariz pequeña","nariz fina",   "gafas"],
            ["Alex",    "hombre",   "corto","negro","negra","oscuro","oscura",                              "finas",    "alargada","alegre","contento","contenta",                  "marrones",                 "boca grande",      "nariz pequeña","nariz fina",   "bigote","barba"],
            ["Sam",     "hombre",   "corto","calvo","calva","blanco","blanca","canoso","canosa","canas",    "finas",    "redonda","redondeada","alegre","contento","contenta",      "marrones",                 "boca pequeña",     "nariz pequeña","nariz fina",   "gafas"],
            ["Richard", "hombre",   "corto","calvo","calva","castaño","castaña",                            "finas",    "alargada","alegre","contento","contenta",                  "marrones",                 "boca pequeña",     "nariz pequeña","nariz fina",   "bigote","barba"],
            ["Paul",    "hombre",   "corto","blanco","blanca","canoso","canosa","canas",                    "gruesas",  "alargada","alegre","contento","contenta",                  "marrones",                 "boca pequeña",     "nariz pequeña","nariz fina",   "gafas"],
            ["Maria",   "mujer",    "largo","castaño","castaña",                                            "finas",    "alargada","alegre","contento","contenta",                  "marrones",                 "boca pequeña",     "nariz pequeña","nariz fina",   "sombrero","gorro","gorra","pendientes","pendiente"],
            ["Frans",   "hombre",   "corto","pelirrojo","pelirroja","rojo","roja",                          "gruesas",  "redonda","redondeada","alegre","contento","contenta",      "marrones",                 "boca pequeña",     "nariz pequeña","nariz fina"    ],
            ["Herman",  "hombre",   "corto","calvo","calva","pelirrojo","pelirroja","rojo","roja",          "gruesas",  "redonda","redondeada","alegre","contento","contenta",      "marrones",                 "boca pequeña",     "nariz grande","nariz gruesa"   ],
            ["Bernard", "hombre",   "corto","castaño","castaña",                                            "finas",    "alargada","triste","enfadado","enfadada",                  "marrones",                 "boca pequeña",     "nariz grande","nariz gruesa",  "sombrero","gorro","gorra"],
            ["Philip",  "hombre",   "corto","negro","negra","oscuro","oscura",                              "finas",    "redonda","redondeada","alegre","contento","contenta",      "marrones",                 "boca grande",      "nariz pequeña","nariz fina",   "mejillas","sonrosadas","bigote","barba"],
            ["Eric",    "hombre",   "corto","rubio","rubia","amarillo","amarilla",                          "finas",    "redonda","redondeada","alegre","contento","contenta",      "marrones",                 "boca grande",      "nariz pequeña","nariz fina",   "sombrero","gorro","gorra"],
            ["Charles", "hombre",   "corto","rubio","rubia","amarillo","amarilla",                          "finas",    "alargada","alegre","contento","contenta",                  "marrones",                 "boca grande",      "nariz pequeña","nariz fina"    ],
            ["Peter",   "hombre",   "corto","blanco","blanca","canoso","canosa","canas",                    "gruesas",  "redonda","redondeada","alegre","contento","contenta",      "azules","azulados",        "boca grande",      "nariz grande","nariz gruesa"   ]]





